### ISSUE TITLE
Issue report or feature request

### ISSUE THREAD

**Issue by SunilP-WassDigital** [bigcommerce/b2b-buyer-portal#157]
**Please fill out this template to help us diagnose and address your issue effectively.**

**Type:** (Select one)
- [ ] Bug Report

**Summary:**
While doing deploy on server and getting below error

```
> `src/utils/loginInfo.ts(117,31): error TS2345: Argument of type '{ storeHash: string; channel_id: number; expires_at: number; allowed_cors_origins: Location[]; }' is not assignable to parameter of type 'Partial<ApiTokenConfig>'.
> 10:44:52 AM: storefront:build:   Types of property 'allowed_cors_origins' are incompatible.
> 10:44:52 AM: storefront:build:     Type 'Location[]' is not assignable to type 'string[]'.
> 10:44:52 AM: storefront:build:       Type 'Location' is not assignable to type 'string'.`
```

Can you please help to me solve it;?

**Comment by bc-micah** [comment]
@BrianJiang2021 - seems like the type introduced in #128 is too restrictive 

https://github.com/bigcommerce/b2b-buyer-portal/blob/58d1daa4735b64b37273f9e327443029531a7883/apps/storefront/src/shared/service/b2b/graphql/login.ts#L9

Can we check on this?

**Comment by BrianJiang2021** [comment]
@SunilP-WassDigital 

A related pr has been created

cc: @bc-micah

**Comment by bc-victor** [comment]
hey @BrianJiang2021 has this issue been solved now by that PR?

**Comment by BrianJiang2021** [comment]
Hi, @bc-victor 

PR: https://github.com/bigcommerce/b2b-buyer-portal/pull/159

production has not yet been deployed
